FROM node:20-alpine3.17 as build
# Указываем образ из dockerhub на основе которого будет работать наш образ

WORKDIR /client/
# Указываем корневую директорию

COPY package*.json /client/
# Копируем package.json в папку сервера

RUN npm install
# устанавливаем зависимости

COPY . /client/
# копируем остальные файлы сервера в образ

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /build /usr/share/nginx/html
COPY --from=build nginx.conf /etc/nginx/sites-enabled/default

EXPOSE 443
# Слушаем порт

CMD ["nginx", "-g", "daemon off;"]