FROM node:20-alpine3.17
# Указываем образ из dockerhub на основе которого будет работать наш образ

WORKDIR /server/
# Указываем корневую директорию

COPY package*.json /server/
# Копируем package.json в папку сервера

RUN npm install
# устанавливаем зависимости

COPY . /server/
# копируем остальные файлы сервера в образ

EXPOSE 6622
# Слушаем порт

COPY ./startup.sh /server/
# Копируем скрипт запуска в контейнер

RUN chmod +x /server/startup.sh
# добавляем разрешение на выполнение для всех пользователей к существующим разрешениям

ENTRYPOINT [ "sh", "/server/startup.sh" ]
# указываем точку входа, запуская файл с командами терминала

# docker tag server:1.0 antonatnagulov/eagles
# docker push antonatnagulov/eagles

# postgresql://postgres:!k7g%hbDbJf@db.wjfwbtqoomdnjrzhmtbr.supabase.co:5432/postgres
# postgresql://postgres:4SUrzdmSW1UZo3mc@db.epqpivvhcwxvrczzyvea.supabase.co:5432/postgres